// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var johny = {
  name: "John",
  age: 12
};

var aliasAge = johny.age;

var coordinates = /* tuple */[
  17,
  53
];

var x = 17;

var y = 53;

export {
  coordinates ,
  x ,
  y ,
  johny ,
  aliasAge ,
  
}
/* No side effect */
