// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function welcomeMessage(name) {
  return "Hello " + name;
}

function longFunction(name) {
  return "Hello " + (name + " !");
}

function add(x, y) {
  return x + y | 0;
}

function add5(param) {
  return 5 + param | 0;
}

var result_15 = 15;

((
  function findCoordinates(latitude, longitude) {
      return;
  }

  findCoordinates(51.1079, 17.0385);
));

((
  function betterFindCoordinates({ latitude, longitude }) {
      return;
  }

  betterFindCoordinates({
      latitude: 51.1079,
      longitude: 17.0385,
  });
));

function findCoords(latitude, longitude) {
  return "You are in Wroclaw";
}

function neverTerminate(_param) {
  while(true) {
    _param = /* () */0;
    continue ;
  };
}

var message = "Hello Dev Meeting";

var add5to6 = 11;

var youAre = "You are in Wroclaw";

export {
  welcomeMessage ,
  longFunction ,
  message ,
  add ,
  add5to6 ,
  add5 ,
  result_15 ,
  findCoords ,
  youAre ,
  neverTerminate ,
  
}
/*  Not a pure module */
