// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var result = "Luke is online";

var $$short = "Online";

var isActive = true;

export {
  isActive ,
  result ,
  $$short ,
  
}
/* No side effect */
