// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var fullTime = 18;

var showWelcomeMessage = true;

if (showWelcomeMessage) {
  console.log("How are you so far?");
}

console.log("Luke");

var name = "Matt";

console.log(name);

var trick = "hello world";

var welcomeMessage = "Hello DevMeetings!";

var startHour = 10;

export {
  welcomeMessage ,
  startHour ,
  fullTime ,
  showWelcomeMessage ,
  name ,
  trick ,
  
}
/*  Not a pure module */
