// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var add_floats = 12 + -12.0;

var float_divisionAndMultiplication = 2.5 / 23 * 1.9;

var isLess = 2 < 3;

var and_ = true;

var or_ = isLess || false;

var isReference = and_ === and_;

var isStructuralOrDeepEquality = and_ === or_;

var participants = /* array */[
  "Rachel",
  "Monica",
  "Phoebe",
  "Joey",
  "Chandler",
  "Ross"
];

var joey = {
  name: "Joey Tribbiani",
  age: 30,
  weight: 80,
  friends: participants
};

var WorkShop_previousVersions = /* :: */[
  0,
  /* :: */[
    1,
    /* :: */[
      2,
      /* :: */[
        3,
        /* [] */0
      ]
    ]
  ]
];

var WorkShop = {
  name: "ReasonML",
  sign: /* "R" */82,
  version: 4,
  duration: 12.4,
  add_ints: 0,
  add_floats: add_floats,
  int_divisionAndMultiplication: 0,
  float_divisionAndMultiplication: float_divisionAndMultiplication,
  helloWorld: "Hello World",
  isMore: true,
  isLess: isLess,
  isMoreOrEqual: true,
  isLessOrEqual: false,
  nagation: false,
  and_: and_,
  or_: or_,
  isReference: isReference,
  isStructuralOrDeepEquality: isStructuralOrDeepEquality,
  previousVersions: WorkShop_previousVersions,
  participants: participants,
  joey: joey
};

export {
  WorkShop ,
  
}
/* isReference Not a pure module */
