// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function checkAnswer(arg) {
  if (arg !== undefined) {
    if (arg) {
      return "Player answers NO";
    } else {
      return "Player answers YES";
    }
  } else {
    return "Player does not answer";
  }
}

var notAnswered = undefined;

var answeredWithYes = /* Yes */0;

var answeredWithNo = /* No */1;

export {
  notAnswered ,
  answeredWithYes ,
  answeredWithNo ,
  checkAnswer ,
  
}
/* No side effect */
