// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var lukeWithJoeyAge = {
  name: "Luke Skywalker",
  age: 30
};

var pat = {
  name: "Pat",
  age: 17
};

pat.age = pat.age + 1 | 0;

var joey = {
  name: "Joey Tribbiani",
  age: 30
};

var name = "Joey Tribbiani";

var age = 30;

var luke = {
  name: "Luke Skywalker",
  age: 53
};

export {
  joey ,
  name ,
  age ,
  luke ,
  lukeWithJoeyAge ,
  pat ,
  
}
/*  Not a pure module */
