// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function getTitleWithWritters(bookTuple) {
  return /* tuple */[
          bookTuple[0],
          bookTuple[2]
        ];
}

var d3coordinates = /* tuple */[
  51.1079,
  17.0385,
  1
];

var book = /* tuple */[
  "Title",
  1990,
  /* :: */[
    "author",
    /* :: */[
      "sub author",
      /* [] */0
    ]
  ]
];

var x = 51.1079;

var y = 17.0385;

var z = 1;

export {
  d3coordinates ,
  book ,
  x ,
  y ,
  z ,
  getTitleWithWritters ,
  
}
/* No side effect */
