// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";

var statusCode200 = /* Ok */Block.__(0, [200]);

var filled = statusCode200;

var questionOne = /* Yes */0;

var questionTwo = /* IDoNotKnow */2;

var errorMessage = /* Error */Block.__(1, ["not_found"]);

var loading = /* Loading */0;

var empty = undefined;

export {
  questionOne ,
  questionTwo ,
  statusCode200 ,
  errorMessage ,
  loading ,
  empty ,
  filled ,
  
}
/* No side effect */
