// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function make(label, handleCheckboxChange) {
  var match = React.useState((function () {
          return false;
        }));
  var setIsChecked = match[1];
  var toggleCheckboxChange = React.useCallback((function (param) {
          Curry._1(setIsChecked, (function (prevState) {
                  return !prevState;
                }));
          return Curry._1(handleCheckboxChange, label);
        }));
  return React.createElement("label", undefined, React.createElement("input", {
                  checked: match[0],
                  type: "checkbox",
                  value: label,
                  onChange: toggleCheckboxChange
                }), React.createElement("span", {
                  className: "checkmark"
                }, label));
}

export {
  make ,
  
}
/* react Not a pure module */
