// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Random from "bs-platform/lib/es6/random.js";

var initialState = {
  count: 0
};

function reducer(state, action) {
  if (typeof action === "number") {
    switch (action) {
      case /* Increment */0 :
          return {
                  count: state.count + 1 | 0
                };
      case /* Decrement */1 :
          return {
                  count: state.count - 1 | 0
                };
      case /* Reset */2 :
          return initialState;
      
    }
  } else {
    return {
            count: action[0]
          };
  }
}

function Counter(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  return React.createElement("div", {
              className: "sort"
            }, React.createElement("span", undefined, "Current state: " + String(match[0].count)), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Increment */0);
                    })
                }, "+"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Decrement */1);
                    })
                }, "-"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Reset */2);
                    })
                }, "Reset"), React.createElement("button", {
                  onClick: (function (param) {
                      Random.self_init(/* () */0);
                      return Curry._1(dispatch, /* SetCount */[Random.$$int(100)]);
                    })
                }, "Set magic number"));
}

var make = Counter;

export {
  initialState ,
  reducer ,
  make ,
  
}
/* react Not a pure module */
