// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function StarButton(Props) {
  var name = Props.name;
  return React.createElement("div", {
              className: "star-button-container"
            }, React.createElement("span", undefined, "Hello" + (name + "\xf0\x9f\x91\x8b ")));
}

var make = StarButton;

export {
  make ,
  
}
/* react Not a pure module */
